### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by bartclaeys** [uploadcare/uploadcare-wordpress#29]
Wordpress version: Version 4.9.8 
PHP version: 7.2.11
PHP Memory limit setting: 128
PHP Upload size setting: 100
Filesize of file to be uploaded: 6MB

After selecting images in the Uploadcare widget and clicking "Add", the spinner keeps spinning forever. When researching what's going on using browser inspection tools, I noticed a 500 error when trying to post to the endpoint:

`https://www.mydomain.com/blog/wp-admin/admin-ajax.php`

Even when you directly visit the below URL (GET request instead of POST) the error appears:

`https://www.mydonain.com/blog/wp-admin/admin-ajax.php?action=uploadcare_handle`

When changing the `action` parameter to another value than `uploadcare_handle` the error disappears. When disabling all other plugins and only enabling the Uploadcare plugin, the error appears, so other plugins don't seem to be the cause.

**Comment by bartclaeys** [comment]
Enabled debugging in `wp-config.php`:

```
define( 'WP_DEBUG', true );
// Debug log file is /wp-content/debug.log:
define( 'WP_DEBUG_LOG', true );
// Disable display of errors and warnings not to distract visitors any longer
define( 'WP_DEBUG_DISPLAY', false );
ini_set( 'display_errors', 0 );
// Use developer versions of core JS and CSS files when you need so:
define( 'SCRIPT_DEBUG', true );
```

**Comment by dmitry-mukhin** [comment]
definitely we need to strip whitespaces on settings page.
thanks for reminding.

**Comment by bartclaeys** [comment]
Why not validate the settings once saved? Would have saved me hours, because I had not clue the 500 error had anything to do with a wrong key. Often 500 is server related.

**Comment by dmitry-mukhin** [comment]
That 500 is WP's thing. It does not expect to get 400 as you can see in the stack trace.
In #31 I proposed exactly that, validate keys when saving the settings.
