### ISSUE TITLE
Support for CDN base?

### ISSUE THREAD

**Issue by bartclaeys** [uploadcare/uploadcare-wordpress#30]
In the field `Widget fine tuning` field on the settings page of the Uploadcare plugin I've entered the following, but it does not have any effect:

`var UPLOADCARE_CDN_BASE = 'https://cdn2.mydomain.com/';`

**Comment by dmitry-mukhin** [comment]
To clarify, what effect do you expect to get?

**Comment by bartclaeys** [comment]
What I expect is the return URL containing my CDN base, instead of `ucarecdn.com`.
