### ISSUE TITLE
WP plugin conflict with WPML Media Translation

### ISSUE THREAD

**Issue by rsedykh** [uploadcare/uploadcare-wordpress#49]
https://wordpress.org/support/topic/uploadcare-wpml-media-translation/

If we can fix it, let's fix it.

**Comment by joshuadelange** [comment]
Hello there, thanks for creating the uploadcare plugin. It works really great.

I am still having issues with this issue with the uploadcare plugin version 3.0.5 and WPML version 4.4.10.

Any ideas on workarounds would be very welcome. Let me know if you need more info from me.

**Comment by joshuadelange** [comment]
After looking into it I was able to find a fix for this issue.

Under WPML > Settings > Custom Field Translations I added the upload care custom fields.

And then I added this filter:

```
add_filter( 'wpml_apply_save_attachment_actions', 'sync_attachment_meta_data', 10, 2 );
function sync_attachment_meta_data( $is_enabled, $post_id ) {
    return true;
}
```

There are still some other uploadcare + wpml issues, but the above should should be enough for original issue.

**Comment by rsedykh** [comment]
Hey @joshuadelange. The best idea we can come up with is to create a list of known compatibility issues with other plugins. :-( We just can't predict them and often can't really solve them without manually tweaking and hacking every single case.

**Comment by joshuadelange** [comment]
Hi @rsedykh , that makes a lot of sense. I think a lot of people could be helped with some documentation on the known issues.
